# Generated by Django 4.1.4 on 2022-12-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('artist_pict', models.ImageField(blank=True, upload_to='artists/')),
                ('num_stars', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
